WITH TEMP AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) as FAVORITES
    from REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO AS RI
JOIN TEMP ON RI.FOOD_TYPE=TEMP.FOOD_TYPE AND RI.FAVORITES=TEMP.FAVORITES
ORDER BY RI.FOOD_TYPE DESC