WITH TEMP AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE  AS UGF
JOIN TEMP ON UGF.BOARD_ID = TEMP.BOARD_ID
ORDER BY FILE_ID DESC